apiVersion: v1
kind: Secret
metadata:
  name: campconnect-secrets
  namespace: campconnect
  labels:
    app.kubernetes.io/name: campconnect
type: Opaque
stringData:
  # IMPORTANT: Change this secret in production!
  APP_JWTSECRET: "CampConnectSecretKeyForJwtTokenGenerationWhichShouldBeLongEnoughToMeetRequirements"
