spring.application.name=campconnect-backend
server.port=8089

# MongoDB Configuration
spring.data.mongodb.uri=mongodb://localhost:27017/campconnectdb

# JWT Configuration (Change this in production)
app.jwtSecret=CampConnectSecretKeyForJwtTokenGenerationWhichShouldBeLongEnoughToMeetRequirements
app.jwtExpirationMs=86400000
